version: '3'

services:

  quailly-egg:
    restart: always
    build:
      context: ./quailly-egg
    hostname: quailly
    ports:
      - 20000:20000
    networks:
      - backend

  db-quailly:
    restart: always
    image: postgres:12.2-alpine
    hostname: db-quailly
    volumes:
      - db-quailly-data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME:quailly}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:quailly}
      POSTGRES_DB: quailly
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  db-quailly-data:
