version: '3'

services:

  quailly-egg:
    container_name: quailly
    restart: always
    build:
      context: ./quailly-egg
    hostname: quailly
    ports:
      - 20000:20000
    networks:
      - backend

  db-quailly:
    container_name: db-quailly
    restart: always
    image: postgres:12.2-alpine
    hostname: db-quailly
    volumes:
      - db-quailly:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=quailly
      - POSTGRES_PASSWORD=quailly
      - POSTGRES_DB=quailly
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  db-quailly:
