version: '3'

services:

  quilly-egg:
    restart: always
    build:
      context: ./quailly-egg
    hostname: quailly
    ports:
      - 20000:20000
    networks:
      - backend

  db-quailly:
    restart: always
    image: postgres:12.1-alpine
    hostname: db-quailly
    volumes:
      - :/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      - PGPORT=5432
      - USER_NAME=quailly
      - DB_NAME=quailly
      - SCHEMA_NAME=quailly
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=UTC
    networks:
      - backend

networks:
  backend:
  frontend: