spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:quailly}
    password: ${SPRING_DATASOURCE_PASSWORD:quailly}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-quailly/quailly}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:20000}