spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:quailly}
    password: ${SPRING_DATASOURCE_PASSWORD:quailly}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-quailly/quailly}
server:
  port: ${PORT:20000}

quailly:
  server:
    zone-id: "Europe/Moscow"

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
  api-docs:
    path: "/api-docs"
