spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:quailly}
    password: ${SPRING_DATASOURCE_PASSWORD:quailly}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-quailly/quailly}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 995330817155-dot2044o2bt5ev47b47okbig7kp4lfjm.apps.googleusercontent.com
            client-secret: 6eIjP1Vpzvu457ulMGtxF-RO

server:
  port: ${PORT:20000}