spring:
  datasource:
    username: quailly
    password: quailly
    url: jdbc:postgresql://db-quailly/quailly
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 20000